import Image from "next/image";
import Link from "next/link";
import { LifeEventCard } from "@/components/life-event-card";
import { GrowthSummary } from "@/components/growth-summary";
import { events, getMediaForEvent, growthRecords, media, monthlySnapshot, profile } from "@/lib/mock-data";

function ageLabel() { return "1 岁 7 个月"; }
export default function HomePage() { const recent = events.slice(0, 3); return <div><section className="home-hero wrap"><div className="hero-copy reveal"><span className="eyebrow">A living archive · 2026.08</span><h1 className="serif">张年，<br /><em>每天都在长大。</em></h1><p>{profile.bio}</p><div className="hero-facts"><span>出生于 2025.01.03</span><span>现在 {ageLabel()}</span></div><Link className="text-link" href="/timeline">进入张年的时间线 <b>↗</b></Link></div><div className="hero-photo reveal reveal-2"><Image src={media[2].src} alt={media[2].alt} fill priority sizes="(max-width: 700px) 100vw, 55vw" style={{ objectFit: "cover" }} /><span className="photo-caption">张年 · 向前走的下午</span></div></section><section className="recent-section wrap"><div className="section-intro"><span className="eyebrow">The latest chapters</span><h2 className="serif">最近发生的事</h2><p>生活没有大事记，只有一件件值得记住的小事。</p></div><div className="recent-grid">{recent.map((event, index) => <LifeEventCard key={event.id} event={event} mediaItem={getMediaForEvent(event)[0]} featured={index === 0} />)}</div></section><div className="wrap home-split"><GrowthSummary records={growthRecords} /><section className="memories"><span className="eyebrow">A few bright spots</span><h2 className="serif">闪光时刻</h2><div className="memory-stack">{events.slice(1, 3).map((event) => <Link href={`/events/${event.id}`} key={event.id}><span>{event.occurredAt.slice(5).replace("-", ".")}</span><strong className="serif">{event.title}</strong><i>↗</i></Link>)}</div></section></div><section className="monthly-note wrap"><span className="eyebrow">August, in one sentence</span><p className="serif">“{monthlySnapshot.summary}”</p><Link className="text-link" href="/timeline">翻回这一个月 <b>↗</b></Link></section><BottomNav /></div>; }
function BottomNav() { return <nav className="bottom-nav" aria-label="移动端主导航"><Link href="/">首页</Link><Link href="/timeline">时间线</Link><Link href="/#growth">成长</Link></nav>; }
