// PostgreSQL/Drizzle source of truth for the production repository.
// The JSON repository is a credential-free local development adapter.
import { pgTable, text, timestamp, integer, boolean, jsonb, primaryKey, unique } from "drizzle-orm/pg-core";

export const profiles = pgTable("profiles", { id: text("id").primaryKey(), displayName: text("display_name").notNull(), birthDate: text("birth_date").notNull(), timezone: text("timezone").notNull(), bio: text("bio"), visibility: text("visibility").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const contributors = pgTable("contributors", { id: text("id").primaryKey(), profileId: text("profile_id").notNull(), displayName: text("display_name").notNull(), relationship: text("relationship").notNull(), type: text("type").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const rawSources = pgTable("raw_sources", { id: text("id").primaryKey(), profileId: text("profile_id").notNull(), contributorId: text("contributor_id").notNull(), sourceType: text("source_type").notNull(), contentTypes: jsonb("content_types").$type<string[]>().notNull(), capturedAt: timestamp("captured_at").notNull(), importedAt: timestamp("imported_at").defaultNow().notNull(), text: text("text"), status: text("status").notNull(), visibility: text("visibility").notNull(), originalFilename: text("original_filename"), metadata: jsonb("metadata"), deletedAt: timestamp("deleted_at"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const mediaAssets = pgTable("media_assets", { id: text("id").primaryKey(), profileId: text("profile_id").notNull(), rawSourceId: text("raw_source_id"), mediaType: text("media_type").notNull(), mimeType: text("mime_type").notNull(), width: integer("width"), height: integer("height"), durationSeconds: integer("duration_seconds"), takenAt: timestamp("taken_at"), checksum: text("checksum"), originalFilename: text("original_filename"), archiveStatus: text("archive_status").notNull().default("awaiting_archive"), archiveVerifiedAt: timestamp("archive_verified_at"), archiveLastError: text("archive_last_error"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const mediaLocations = pgTable("media_locations", { id: text("id").primaryKey(), mediaAssetId: text("media_asset_id").notNull(), provider: text("provider").notNull(), variant: text("variant").notNull(), providerRef: text("provider_ref").notNull(), mimeType: text("mime_type"), fileSize: integer("file_size"), width: integer("width"), height: integer("height"), status: text("status").notNull(), quarkPathSnapshot: text("quark_path_snapshot"), sourceParentRef: text("source_parent_ref"), sourceCreatedAt: timestamp("source_created_at"), sourceUpdatedAt: timestamp("source_updated_at"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (table) => ({ assetVariant: unique().on(table.mediaAssetId, table.provider, table.variant), providerRef: unique().on(table.provider, table.providerRef) }));
export const lifeEvents = pgTable("life_events", { id: text("id").primaryKey(), profileId: text("profile_id").notNull(), title: text("title"), story: text("story"), occurredAt: timestamp("occurred_at").notNull(), contentTypes: jsonb("content_types").$type<string[]>().notNull(), memoryWeight: text("memory_weight").notNull(), featured: boolean("featured").default(false).notNull(), yearbookSelected: boolean("yearbook_selected").default(false).notNull(), visibility: text("visibility").notNull(), createdBy: text("created_by"), organizerVersion: text("organizer_version"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const sourceMemoryLinks = pgTable("source_memory_links", { rawSourceId: text("raw_source_id").notNull(), lifeEventId: text("life_event_id").notNull(), role: text("role").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() }, (table) => ({ pk: primaryKey({ columns: [table.rawSourceId, table.lifeEventId] }) }));
export const connectorStates = pgTable("connector_states", { id: text("id").primaryKey(), provider: text("provider").notNull(), profileId: text("profile_id").notNull(), cursor: text("cursor"), lastSuccessfulSync: timestamp("last_successful_sync"), lastError: text("last_error"), pendingArchiveCount: integer("pending_archive_count").notNull().default(0), scope: jsonb("scope"), connectorVersion: text("connector_version").notNull(), status: text("status").notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(), lastKeyword: text("last_keyword"), lastAttemptAt: timestamp("last_attempt_at"), lastSuccessfulAt: timestamp("last_successful_at"), artifactItemCount: integer("artifact_item_count"), importedCount: integer("imported_count"), failedCount: integer("failed_count"), lastErrorCode: text("last_error_code") });
export const organizerRuns = pgTable("organizer_runs", { id: text("id").primaryKey(), profileId: text("profile_id").notNull(), organizationFingerprint: text("organization_fingerprint").notNull().unique(), organizerType: text("organizer_type").notNull(), organizerVersion: text("organizer_version").notNull(), provider: text("provider").notNull(), model: text("model"), promptVersion: text("prompt_version"), action: text("action").notNull(), sourceIds: jsonb("source_ids").$type<string[]>().notNull(), targetId: text("target_id"), sourceCount: integer("source_count").notNull(), mediaInputCount: integer("media_input_count").notNull(), processedAt: timestamp("processed_at").notNull(), fallbackReason: text("fallback_reason"), latencyMs: integer("latency_ms"), tokenUsage: jsonb("token_usage") });
