CREATE TABLE IF NOT EXISTS profiles (id text PRIMARY KEY, display_name text NOT NULL, birth_date text NOT NULL, timezone text NOT NULL, bio text, visibility text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS contributors (id text PRIMARY KEY, profile_id text NOT NULL, display_name text NOT NULL, relationship text NOT NULL, type text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS raw_sources (id text PRIMARY KEY, profile_id text NOT NULL, contributor_id text NOT NULL, source_type text NOT NULL, content_types jsonb NOT NULL, captured_at timestamptz NOT NULL, imported_at timestamptz NOT NULL DEFAULT now(), text text, status text NOT NULL, visibility text NOT NULL, original_filename text, metadata jsonb, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
-- Media binary is deliberately outside Postgres. One logical asset can have many
-- locations: Quark original + hot web derivatives (or a local development copy).
CREATE TABLE IF NOT EXISTS media_assets (id text PRIMARY KEY, profile_id text NOT NULL, raw_source_id text, media_type text NOT NULL, mime_type text NOT NULL, width integer, height integer, duration_seconds integer, taken_at timestamptz, checksum text, original_filename text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS media_locations (id text PRIMARY KEY, media_asset_id text NOT NULL, provider text NOT NULL, variant text NOT NULL, provider_ref text NOT NULL, mime_type text, file_size integer, width integer, height integer, status text NOT NULL, quark_path_snapshot text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (media_asset_id, provider, variant));
CREATE TABLE IF NOT EXISTS life_events (id text PRIMARY KEY, profile_id text NOT NULL, title text, story text, occurred_at timestamptz NOT NULL, content_types jsonb NOT NULL, memory_weight text NOT NULL, featured boolean NOT NULL DEFAULT false, yearbook_selected boolean NOT NULL DEFAULT false, visibility text NOT NULL, created_by text, organizer_version text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS source_memory_links (raw_source_id text NOT NULL, life_event_id text NOT NULL, role text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (raw_source_id, life_event_id));
CREATE TABLE IF NOT EXISTS connector_states (id text PRIMARY KEY, provider text NOT NULL, profile_id text NOT NULL, cursor text, last_successful_sync timestamptz, version text NOT NULL, status text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
