ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS archive_status text NOT NULL DEFAULT 'awaiting_archive';
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS archive_verified_at timestamptz;
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS archive_last_error text;
ALTER TABLE connector_states ADD COLUMN IF NOT EXISTS last_error text;
ALTER TABLE connector_states ADD COLUMN IF NOT EXISTS pending_archive_count integer NOT NULL DEFAULT 0;
ALTER TABLE connector_states ADD COLUMN IF NOT EXISTS scope jsonb;
ALTER TABLE connector_states ADD COLUMN IF NOT EXISTS connector_version text;
UPDATE connector_states SET connector_version = COALESCE(connector_version, 'quark-connector/0.1');
ALTER TABLE connector_states ALTER COLUMN connector_version SET DEFAULT 'quark-connector/0.1';
ALTER TABLE connector_states ALTER COLUMN connector_version SET NOT NULL;
